import crypto from 'node:crypto';
import { ElevenLabsClient, type ElevenLabs } from '@elevenlabs/elevenlabs-js';
import { eq, sql } from 'drizzle-orm';
import { db, schema } from './db';

/**
 * Text to speech, server side only.
 *
 * The API key never reaches the browser. The page asks this server for audio and
 * plays the bytes it gets back. The SDK's play() helper is not used anywhere: it
 * is Node-only and shells out to a local audio player, so it cannot work for a
 * browser client.
 *
 * Caching is the whole reason this is careful. An AAC communicator presses
 * "more" dozens of times a day, and every press would otherwise be billed
 * again. Audio is cached by text + voice + model.
 *
 * THE GOTCHA: convert() returns a STREAM. If the stream itself were cached, the
 * first hit would consume it and every later hit would get an empty, already
 * read stream. So it is fully buffered into bytes before it is stored, and bytes
 * are what the cache hands back.
 */

/**
 * eleven_flash_v2_5 during development, about half the cost of multilingual.
 * Swap ELEVENLABS_MODEL_ID to eleven_multilingual_v2 for the demo; nothing else
 * has to change. The cache key includes the model, so switching models does not
 * serve back audio generated by the old one.
 */
const MODEL_ID = process.env.ELEVENLABS_MODEL_ID || 'eleven_flash_v2_5';
const OUTPUT_FORMAT = (process.env.ELEVENLABS_OUTPUT_FORMAT ||
  'mp3_44100_128') as ElevenLabs.TextToSpeechConvertRequestOutputFormat;
const MIME = 'audio/mpeg';

export function isTtsConfigured(): boolean {
  return Boolean(process.env.ELEVENLABS_API_KEY);
}

let client: ElevenLabsClient | null = null;
function getClient(): ElevenLabsClient {
  if (!client) {
    client = new ElevenLabsClient({ apiKey: process.env.ELEVENLABS_API_KEY });
  }
  return client;
}

function cacheKeyFor(text: string, voiceId: string, modelId: string): string {
  return crypto.createHash('sha256').update(`${modelId}|${voiceId}|${text}`).digest('hex');
}

/**
 * Drains whatever convert() returned into a single Buffer.
 *
 * Handles a web ReadableStream, a Node readable / async iterable, and a plain
 * byte array, because the exact shape depends on the SDK version and runtime.
 */
async function toBuffer(audio: unknown): Promise<Buffer> {
  if (!audio) throw new Error('No audio returned from ElevenLabs.');

  if (Buffer.isBuffer(audio)) return audio;
  if (audio instanceof Uint8Array) return Buffer.from(audio);
  if (audio instanceof ArrayBuffer) return Buffer.from(new Uint8Array(audio));

  // Web ReadableStream
  const maybeWeb = audio as ReadableStream<Uint8Array>;
  if (typeof (maybeWeb as { getReader?: unknown }).getReader === 'function') {
    const reader = maybeWeb.getReader();
    const chunks: Uint8Array[] = [];
    for (;;) {
      const { done, value } = await reader.read();
      if (done) break;
      if (value) chunks.push(value);
    }
    return Buffer.concat(chunks.map((c) => Buffer.from(c)));
  }

  // Node stream or any async iterable of chunks
  const maybeIterable = audio as AsyncIterable<Uint8Array | Buffer>;
  if (typeof (maybeIterable as { [Symbol.asyncIterator]?: unknown })[Symbol.asyncIterator] === 'function') {
    const chunks: Buffer[] = [];
    for await (const chunk of maybeIterable) {
      chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk));
    }
    return Buffer.concat(chunks);
  }

  throw new Error('Unrecognised audio payload from ElevenLabs.');
}

export interface SpeechResult {
  bytes: Buffer;
  mime: string;
  cached: boolean;
  charCount: number;
  modelId: string;
  voiceId: string;
}

function readCache(cacheKey: string) {
  return db.select().from(schema.audioCache).where(eq(schema.audioCache.cacheKey, cacheKey)).get();
}

/**
 * Returns spoken audio for this text, from cache when possible.
 * A cache hit costs nothing and spends no characters.
 */
export async function synthesize(rawText: string, voiceId: string): Promise<SpeechResult> {
  const text = rawText.trim();
  if (!text) throw new Error('Nothing to speak.');
  if (!isTtsConfigured()) throw new Error('ELEVENLABS_API_KEY is not set.');

  const cacheKey = cacheKeyFor(text, voiceId, MODEL_ID);

  const hit = readCache(cacheKey);
  if (hit) {
    db.update(schema.audioCache)
      .set({ hits: sql`${schema.audioCache.hits} + 1` })
      .where(eq(schema.audioCache.cacheKey, cacheKey))
      .run();
    return {
      bytes: Buffer.from(hit.bytes as Buffer),
      mime: hit.mime,
      cached: true,
      charCount: hit.charCount,
      modelId: hit.modelId,
      voiceId: hit.voiceId,
    };
  }

  const audio = await getClient().textToSpeech.convert(voiceId, {
    text,
    modelId: MODEL_ID,
    outputFormat: OUTPUT_FORMAT,
  });

  // Buffer before storing. See the note at the top of this file.
  const bytes = await toBuffer(audio);
  if (bytes.length === 0) throw new Error('ElevenLabs returned empty audio.');

  db.insert(schema.audioCache)
    .values({
      cacheKey,
      text,
      voiceId,
      modelId: MODEL_ID,
      mime: MIME,
      bytes,
      charCount: text.length,
      hits: 0,
    })
    .onConflictDoNothing()
    .run();

  return {
    bytes,
    mime: MIME,
    cached: false,
    charCount: text.length,
    modelId: MODEL_ID,
    voiceId,
  };
}

/** Characters actually sent to ElevenLabs so far, for keeping an eye on credits. */
export function creditsSpent(): { characters: number; clips: number; cacheHits: number } {
  const row = db
    .select({
      characters: sql<number>`coalesce(sum(${schema.audioCache.charCount}), 0)`,
      clips: sql<number>`count(*)`,
      cacheHits: sql<number>`coalesce(sum(${schema.audioCache.hits}), 0)`,
    })
    .from(schema.audioCache)
    .get();
  return row ?? { characters: 0, clips: 0, cacheHits: 0 };
}

export { MODEL_ID as TTS_MODEL_ID };
